### ISSUE TITLE
Think of better name for `meta` in local/global dataset handling

### ISSUE THREAD

**Issue by noxan** [ourownstory/neural_prophet#1016]
Not really sure what `meta_name_bool` stands for, could we come up with some more clear naming? For example `meta_use_df_name` or something similar?

_Originally posted by @noxan in https://github.com/ourownstory/neural_prophet/pull/997#discussion_r1035504420_

**Comment by noxan** [comment]
@alfonsogarciadecorral @karl-richter would be great to have your input on a more clear naming for this functionality. As I understood it the `meta` represents the local id of the dataset in a glocal modelling, is that right?

**Comment by karl-richter** [comment]
Maybe something like `local_dataset_name`? @ourownstory what do you think?

**Comment by alfonsogarciadecorral** [comment]
Now, the only "meta" thing we need, from the dataloader, is the ID/dataset_name. But I thought that meta could include at some point the static covariates as well. 

In that case, for global/local modeling,  `meta_used_in_model` could be used instead of needing one bool for names and one for the static covariates.

**Comment by karl-richter** [comment]
Closed by #997.
