### ISSUE TITLE
Adress all warnings

### ISSUE THREAD

**Issue by karl-richter** [ourownstory/neural_prophet#1159]
Adress all warnings in the pytests.

**Comment by leoniewgnr** [comment]
@karl-richter are you working on this (or in the next three weeks), if not please unassign yourself

**Comment by leoniewgnr** [comment]
**Fixed warnings**
- [x] test_integration.py: neuralprophet/data/process.py:126: DeprecationWarning: The default dtype for empty Series will be 'object' instead of 'float64' in a future version. Specify a dtype explicitly to silence this warning.

**Not addressed and reason**
- [x] neural_prophet/.venv/lib/python3.9/site-packages/plotly_resampler/aggregation/aggregators.py:25: UserWarning: Could not import lttbc; will use a (slower) python alternative.
    warnings.warn("Could not import lttbc; will use a (slower) python alternative.") 
--> will be removed in the near future, see https://github.com/predict-idlab/plotly-resampler/issues/180
- [x] torch: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead. 
--> is already fixed in torch 2.0, see here for the commit, that fixes it: https://github.com/pytorch/pytorch/pull/95545 (merged on Feb 27)
- [x] DeprecationWarning: Deprecated call to `pkg_resources.declare_namespace('pytorch_lightning')`.
  Implementing implicit namespace packages (as specified in PEP 420) is preferred to `pkg_resources.declare_namespace`. See https://setuptools.pypa.io/en/latest/references/keywords.html#keyword-namespace-packages
    __import__("pkg_resources").declare_namespace(__name__)
--> Lightning knows about the warning and are on it, see https://github.com/Lightning-AI/lightning/issues/16756
