### ISSUE TITLE
Supplement the documentation with requirements for df_val to be used in test() method and explain how this method works. 

### ISSUE THREAD

**Issue by vfrankswood** [ourownstory/neural_prophet#1208]
While experimenting with Neural Prophet, I found out that ```.test()```  method (suggested for cross validation) works only if following requirement is met: ```len(df_val) >= n_lags + n_forecasts```. Otherwise, I got ```ValueError: batch_size should be a positive integer value, but got batch_size=0```. 

Is it some kind of bug? because it doesn't make a sense to me. 
If this requirement is essential for cross-validation strategy inside ```.test()``` method, then I think it would be very good to have the ```.test()```method  explained in the documentation and mention the requirement itself.

Code to reproduce the problem:

```
from neuralprophet import NeuralProphet
import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/ejgao/Time-Series-Datasets/master/Electric_Production.csv')
df.columns = ['ds', 'y']
df['ds'] = pd.to_datetime(df['ds'])
df_train = df[:380]  # length 380
df_val = df[380:] # length 17

model = NeuralProphet(n_lags=12, n_forecasts=6)
model.fit(df_train, freq='MS')
model.test(df_val)

# ValueError: batch_size should be a positive integer value, but got batch_size=0
```

The problem exists as long as length of ```df_val``` is smaller than ```n_forecasts+n_lags```.

**Comment by leoniewgnr** [comment]
@vfrankswood yes this is true, as we use in test() a [built in python function](https://github.com/ourownstory/neural_prophet/blob/f61527a454fb94f672f9c89cc5f3fb419224cda9/neuralprophet/forecaster.py#L2699), you are right, acutally it doesn't need to be longer than `n_lags + n_forecasts`, but only longer than `n_forecasts`. 
In our own split function, we set the input_overbleeds parameter to True, so check https://github.com/ourownstory/neural_prophet/blob/f61527a454fb94f672f9c89cc5f3fb419224cda9/neuralprophet/df_utils.py#L822 for further details.
Unfortunately, we have no capacity to work on this, but if you want to, you are more than welcome. Otherwise, we will close the issue.
Best,
Leonie

**Comment by leoniewgnr** [comment]
closed due to inactivity
