### ISSUE TITLE
Not installing on Colab

### ISSUE THREAD

**Issue by ganeshramg** [ourownstory/neural_prophet#196]
pip install neuralprophet/neural_prophet is not working on Google Colab. It shows, no matching distribution found. But I'm able to use it on Jupyter notebook locally. I'd appreciate if someone could help me understand this, or fix this issue. Thanks :)

**Comment by ourownstory** [comment]
Hi @ganeshramg,
If you check `!python --version` in your Colab environment, you will likely fin it to use `Python 3.6.9`

NeuralProphet requires python 3.7 due to the use of `@dataclass`.

We will consider adding backwards compatability in the future. for now, you could figure out how to get your Colab env to use 3.7.

**Comment by ourownstory** [comment]
@ganeshramg 
I made it backwards compatible with python 3.6 for you. tested it on local py 3.6.9 and on a colab notebook. It works now.

Install in colab directly from github with:
`!pip install git+https://github.com/ourownstory/neural_prophet.git`

**Comment by ganeshramg** [comment]
@ourownstory 
Thank you so much. Appreciate your time and efforts!
