### ISSUE TITLE
Monte Carlo distribution from fitted model

### ISSUE THREAD

**Issue by yasirroni** [ourownstory/neural_prophet#509]
**Prerequisites**
   [X] Checked the Answered Questions on the Github Disscussion board: https://github.com/ourownstory/neural_prophet/discussions
   [X] Checked that your issue isn't already filed: https://github.com/ourownstory/neural_prophet/issues
   [X] Considered whether your issue might need further discussing before being defined as a feature request.

**Is your feature request related to a problem? Please describe.**

I want to generate multiple weighted prediction. In `facebook/prophet`, one way is to use posterior sample using `predictive_samples` and clustering. See this [issue](https://github.com/facebook/prophet/issues/1878#issue-867314656).

In NN based algorithm, allowing model to predict multiple value with confidence is also a thing, but in this case, the confidence should be for each set of times (assuming output 5 time series, weight will be for each time series) and not for each points (assuming 1800 future points for each time series, they should got single weight for single time series).

**Describe the solution you'd like**

Monte Carlo generator or multi prediction with confidence for each time series.

**Describe alternatives you've considered**

None in NeuralProphet

**Additional context**

I've digging on the source code of forecaster and can't found any similar `predictive_sample` method.

**Comment by ourownstory** [comment]
Hi @yasirroni

Thank you for your suggestion.
Due to the substantially different fitting procedure and framework that we use for NeuralPropeht compared to Prophet, we did not include a MC utility.

As you point out, this is not impossible with NN, but would require to decide on which approach to take and how to implement it.
This is currently not in scope of near-term improvements planned by the core maintainers.

However, if anyone would like to attempt to create this feature, we would welcome a PR, and be happy to have some chats before you get started.
