### ISSUE TITLE
TypeError: fit() got an unexpected keyword argument 'plot_live_loss'

### ISSUE THREAD

**Issue by rahul4tripathi2** [ourownstory/neural_prophet#572]
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-7-3bd4a209fb82> in <module>
     12 df_train, df_test = m.split_df(sf_pv_df, freq='H', valid_p = 0.10)
     13 
---> 14 metrics = m.fit(df_train, freq='H', validation_df=df_test, plot_live_loss=True)

TypeError: fit() got an unexpected keyword argument 'plot_live_loss'

**Comment by ourownstory** [comment]
Hi @rahul4tripathi2 

We made an API change to make the progress printing less confusing - it is now set with a string. 
See the details here: https://github.com/ourownstory/neural_prophet/blob/a3bc16f2362fc8b08712dd52752c53e4c02dc492/neuralprophet/forecaster.py#L434

Did you get this error because you saw this somewhere in the documentation or tutorials or because you used to use this?

Sorry for the trouble!

**Comment by rahul4tripathi2** [comment]
Thanks for quick response. it fixed our issue.

Yes, i was trying to run below notebook
https://github.com/ourownstory/neural_prophet/blob/main/tutorials/application-example/energy_solar_pv.ipynb

Regards
Rahul

**Comment by ourownstory** [comment]
Thank you @rahul4tripathi2, we updated the tutorials now.
