### ISSUE TITLE
[bug] np.quantile not compatible with python < 3.8

### ISSUE THREAD

**Issue by Mckiler** [ourownstory/neural_prophet#684]
I found some error on energy_solar_pv.ipynb

---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
[<ipython-input-31-bfeb12738ca9>](https://localhost:8080/#) in <module>()
      1 m = NeuralProphet()
----> 2 metrics = m.fit(df_train)
      3 forecast = m.predict(df_test)

6 frames
[/usr/local/lib/python3.7/dist-packages/neuralprophet/df_utils.py](https://localhost:8080/#) in get_normalization_params(array, norm_type)
    340     if norm_type == "soft":
    341         lowest = np.min(non_nan_array)
--> 342         q95 = np.quantile(non_nan_array, 0.95, method="higher")
    343         width = q95 - lowest
    344         if math.isclose(width, 0):

<__array_function__ internals> in quantile(*args, **kwargs)

TypeError: _quantile_dispatcher() got an unexpected keyword argument 'method'

**Comment by rlxm7100** [comment]
I have same issue too.

**Comment by FedericoGarza** [comment]
Hi @Mckiler, @rlxm7100!

I had the same problem. The problem arises from the version of `NumPy` used. The `method` argument of the `np.quantile` function is new as of [`NumPy` version 1.22.1](https://github.com/ourownstory/neural_prophet/issues/684), but that version is only compatible with [python>=3.8](https://numpy.org/devdocs/release/1.22.1-notes.html). 

The solution is to use this version of python (3.8) and install `NumPy` and `neuralprophet`.

@ourownstory It could be useful to include this information in the colab notebooks since the default version in colab is python 3.7.
